// <auto-generated />
namespace team2Geraldton.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class hospital_project : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hospital_project));
        
        string IMigrationMetadata.Id
        {
            get { return "202104151732245_hospital_project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
